name: project
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  awesome_dialog: ^3.2.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  fl_country_code_picker: ^0.1.9+1
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.0.1
  flutter_google_places: ^0.3.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  geocoding: ^3.0.0
  get: ^4.6.6
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.5.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  image_picker: ^1.0.7
  intl: ^0.19.0
  ionicons: ^0.2.2
  pinput: ^5.0.0
  shared_preferences: ^2.2.2
  sms_autofill: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    # - assets/images/
    - assets/
